# Font configuration
font_family                   family="Mononoki Nerd Font"
bold_font                     auto
italic_font                   auto
bold_italic_font              auto
font_size                     10.0
disable_ligatures             cursor

# Cursor
cursor                        #ffffff
cursor_shape                  beam
cursor_shape_unfocused        hollow
cursor_blink_interval         0
cursor_trail                  1000
cursor_trail_decay            0.1 0.3
cursor_trail_threshold        10
cursor_trail_color            #7f7f7f

# Scrollback
scrollback_lines              -1
scrollbar                     hovered
scrollbar_interactive         yes
scrollbar_jump_on_click       yes
scrollbar_width               0.5
scrollbar_hitbox_expansion    0.25

# Mouse
mouse_hide_wait               3.0
url_color                     #29adff
url_style                     curly
detect_urls                   yes
show_hyperlink_targets        yes
copy_on_select                no

# Tabs
tab_bar_edge                  bottom
tab_bar_align                 left
tab_bar_style                 separator
tab_separator                 " | "
active_tab_foreground         #101010
active_tab_background         #7d7d7d
active_tab_font_style         bold
inactive_tab_foreground       #7d7d7d
inactive_tab_background       #101010
active_tab_font_style         normal
tab_bar_background            #101010
