#==============================================
# zsh-newuser-install
#==============================================
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e

#==============================================
# Functions? Currently don't use
#==============================================
fpath+=("${ZDOTDIR}/myfunctions/")

#==============================================
# compinstall
#==============================================
zstyle :compinstall filename "${HOME}/.config/zsh/.zshrc"

autoload -Uz compinit promptinit
# autoload -U colors && colors
compinit
promptinit

#==============================================
# Aliases
#==============================================
source "${ZDOTDIR}/zsh_alias"

#==============================================
# Different options for different terminals
#==============================================
case ${TERM} in 
    xterm-kitty)
        source "${ZDOTDIR}/zsh_term_kitty"
        ;;

    tmux-256color)
        source "${ZDOTDIR}/zsh_term_tmux-256color"
        ;;

    *)
        source "${ZDOTDIR}/zsh_term_other"
        ;;
esac

#==============================================
# Postload
#==============================================
autoload bashcompinit
bashcompinit
source "${HOME}/.local/share/bash-completion/completions/appman"
