### Fonts
font pango:MononokiNerdFont 10

### Special handling for Xwayland apps
for_window [shell="xwayland"] title_format "  %title"
for_window [sandbox_engine="org.flatpak"] title_format "  %title"

## Colors
client.focused #ffc400 #232323 #ffffff #606060
client.unfocused #707070 #232323 #ffffff
client.focused_inactive #232323 #232323 #ffffff
client.focused_tab_title #232323 #232323 #ffffff
client.urgent #ff0000 #232323 #ffffff

### Title position
title_align center
seat seat0 xcursor_theme Posy_Cursor_Black 16
